@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Nzk5MzI1ODd9.HBCVTWncwAJiMVn5xx4x_cVJmb4UM5mDbXBKkLJrrrg

### User Create
POST http://localhost:3000/users.json 
Content-Type: application/json

{
  "name": "Mendel",
  "email": "mendel@test.com",
  "password": "password",
  "image": "user_image.jpg"
}

### Session Create
POST http://localhost:3000/sessions.json 
Content-Type: application/json

{
  "email": "mendel@test.com",
  "password": "password"
}

### Room Index
GET http://localhost:3000/rooms.json
Content-Type: application/json
Authorization: Bearer {{jwt}}


### Room Show
GET http://localhost:3000/rooms/5.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Room Create
POST http://localhost:3000/rooms.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "address": "16 Test Rd.",
  "city": "Your City",
  "state": "Your State",
  "price": 400.00,
  "description": "King Suite",
  "home_type": "single family",
  "room_type": "1 King Bed",
  "total_occupancy": 3,
  "total_bedrooms": 1,
  "total_bathrooms": 1
}

### Room Update
PATCH http://localhost:3000/rooms/5.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "price": 450
}

### Room Delete
DELETE http://localhost:3000/rooms/5.json

### Create a Reservation
POST http://localhost:3000/reservations.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "room_id":1,
  "start_date":20230325,
  "end_date":20230328
}

### Reservation Delete
DELETE http://localhost:3000/reservations/2.json
Authorization: Bearer {{jwt}}

### Reservations Index
GET http://localhost:3000/reservations.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Show one reservation
GET http://localhost:3000/reservations/2.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Review Index
GET http://localhost:3000/reviews
Content-Type: application/json
Authorization: Bearer {{jwt}}


### Review Show
GET http://localhost:3000/reviews/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Review Create
POST http://localhost:3000/reviews.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "reservation_id": 2,
  "rating": 1.0,
  "comment": "HATED THIS PLACE."
}

### Review Update
PATCH http://localhost:3000/reviews/2.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "rating": 1.5,
  "comment": "could be worse"
}

### Review Delete
DELETE http://localhost:3000/reviews/2.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

