@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzk3MDkzMjB9.hfTktpdnI0lbOHFA5kBU6vQwiEeqaVko6W9FggGdQlc

### User Create
POST http://localhost:3000/users.json 
Content-Type: application/json

{
  "name": "Aakash",
  "email": "aakash@test.com",
  "password": "password",
  "image": "user_image.jpg"
}

### Session Create
POST http://localhost:3000/sessions.json 
Content-Type: application/json

{
  "email": "aakash@test.com",
  "password": "password"
}

### Room Index
GET http://localhost:3000/rooms
Content-Type: application/json
Authorization: Bearer {{jwt}}


### Room Show
GET http://localhost:3000/rooms/1.json
Content-Type: application/json

### Room Create
POST http://localhost:3000/rooms.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "user_id": 1,
  "address": "14 Test Rd.",
  "city": "Your City",
  "state": "Your State",
  "price": 200,
  "description": "King Suite",
  "home_type": "single family",
  "room"
}

### Room Update
PATCH http://localhost:3000/rooms/2.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Room Delete
DELETE http://localhost:3000/rooms/1.json

